### ISSUE TITLE
Eno/Lanois shimmer sound

### ISSUE THREAD

**Issue by gogins** [gogins/michael.gogins.studio#43]
> The basic foundation of the Brian Eno / Daniel Lanois shimmer sound is fairly simple: Create a feedback loop, incorporating a pitch shifter set to +1 octave, and a reverb with a fairly long decay time. By controlling the gain and equalization of the feedback loop, and the lengths of the various delays within the loop, the temporal evolution of the sound can be altered from steel drum-esque sounds to the slow attack “string pads” hear on many of the Eno/Lanois tracks. This is the same technique used by ValhallaShimmer, with the reverberation, pitch shifting and feedback all incorporated within the same plugin.

**Comment by gogins** [comment]
I just decided to go ahead and buy Sean's product.

**Comment by gogins** [comment]
What a pain. Maybe try this? https://www.npmjs.com/package/nw-builder

**Comment by gogins** [comment]
- [ ] Create one's application directory.
- [ ] Put into it `package.json` and `index.html`.
- [ ] In that directory run `pnpm add nw-builder -D`.
- [ ] Then run `nwbuilder mode=get` which installs NW.js in the directory..
- [ ] To see if it works run `nwbuilder mode=run`.

**Comment by gogins** [comment]
I'm not sure this is going to work for me. It won't, probably, unless I create a single NW.js app that will run any .html piece.

**Comment by gogins** [comment]
Anyway, it doesn't work anyway!
```
michaelgogins@Michaels-MacBook-Pro ~/nwbuild-test % pnpm nwbuild --mode=get
 ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 100% | ETA: 0s | 126354427/126354427
[ ERROR ] Cannot close while reading in progress
/Users/michaelgogins/nwbuild-test/node_modules/.pnpm/yauzl-promise@4.0.0/node_modules/yauzl-promise/lib/reader.js:62
		assert(this.readCount === 0, 'Cannot close while reading in progress');
		^

Error: Cannot close while reading in progress
    at FileReader.close (/Users/michaelgogins/nwbuild-test/node_modules/.pnpm/yauzl-promise@4.0.0/node_modules/yauzl-promise/lib/reader.js:62:3)
    at Zip.close (/Users/michaelgogins/nwbuild-test/node_modules/.pnpm/yauzl-promise@4.0.0/node_modules/yauzl-promise/lib/zip.js:87:22)
    at file:///Users/michaelgogins/nwbuild-test/node_modules/.pnpm/nw-builder@4.4.2-beta.4/node_modules/nw-builder/src/get.js:257:19
    at async get (file:///Users/michaelgogins/nwbuild-test/node_modules/.pnpm/nw-builder@4.4.2-beta.4/node_modules/nw-builder/src/get.js:90:3)
    at async nwbuild (file:///Users/michaelgogins/nwbuild-test/node_modules/.pnpm/nw-builder@4.4.2-beta.4/node_modules/nw-builder/src/index.js:149:5) {
  level: 'error',
  timestamp: '2023-12-02T03:00:01.324Z',
  [Symbol(level)]: 'error',
  [Symbol(message)]: '[ ERROR ] Cannot close while reading in progress'
}
```

**Comment by gogins** [comment]
OK this worked:
```
pnpm nwbuild --glob=false --mode=run --version=latest --flavor=sdk .
```

**Comment by gogins** [comment]
I opened a separate issue to run .html pieces in both cloud-5 and NW.js.
